#!/bin/sh

#You must to do this file executable in order to run, type 'chmod +x q2p.run'
#QuDos -- http://qudos.quakedev.com

BIN="q2p"
DIR="."

script=$0
count=0
while [ -L "$script" ]  
do
    script=`perl -e "print readlink(\"$script\"), \"\n\""`
    count=`expr $count + 1`
    if [ $count -gt 100 ]  
    then
        echo "Too many symbolic links"
        exit 1
    fi
done

GAME_DIR=`dirname $script`

cd $GAME_DIR
cd $DIR
exec ./$BIN "$@"
